from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


FLUENT_CELL_TYPES = {
    3: 1,  # triangle nodes -> triangular cell
    4: 3,  # quad nodes -> quadrilateral cell
}

FLUENT_BC_TYPES = {
    "interior": 2,
    "plate_wall": 3,
    "inlet": 10,
    "outlet": 5,
    "top": 7,
    "bottom": 7,
    "unassigned_wall": 3,
}

FLUENT_ZONE_TYPES = {
    "interior": "interior",
    "plate_wall": "wall",
    "inlet": "velocity-inlet",
    "outlet": "pressure-outlet",
    "top": "symmetry",
    "bottom": "symmetry",
    "unassigned_wall": "wall",
}


@dataclass(frozen=True)
class FluentFace:
    zone: str
    n0: int
    n1: int
    c0: int
    c1: int


def hx(value: int) -> str:
    return format(value, "x")


def polygon_area(points: list[tuple[float, float]], node_ids: list[int]) -> float:
    area = 0.0
    for idx, node in enumerate(node_ids):
        next_node = node_ids[(idx + 1) % len(node_ids)]
        x0, y0 = points[node - 1]
        x1, y1 = points[next_node - 1]
        area += x0 * y1 - x1 * y0
    return 0.5 * area


def orient_cells_ccw(
    points: list[tuple[float, float]], cells: list[list[int]]
) -> list[list[int]]:
    oriented = []
    for cell in cells:
        if polygon_area(points, cell) < 0:
            oriented.append(list(reversed(cell)))
        else:
            oriented.append(cell)
    return oriented


def build_faces(
    cells: list[list[int]],
    boundary_zones_by_edge: dict[tuple[int, int], str],
) -> list[FluentFace]:
    pending: dict[tuple[int, int], tuple[int, int, int]] = {}
    faces: list[FluentFace] = []

    for cell_id, nodes in enumerate(cells, start=1):
        for idx, n0 in enumerate(nodes):
            n1 = nodes[(idx + 1) % len(nodes)]
            key = tuple(sorted((n0, n1)))
            if key in pending:
                prev_n0, prev_n1, prev_cell = pending.pop(key)
                faces.append(FluentFace("interior", prev_n0, prev_n1, prev_cell, cell_id))
            else:
                pending[key] = (n0, n1, cell_id)

    for key, (n0, n1, cell_id) in pending.items():
        zone = boundary_zones_by_edge.get(key, "unassigned_wall")
        faces.append(FluentFace(zone, n0, n1, cell_id, 0))

    zone_order = ["interior", "inlet", "outlet", "top", "bottom", "plate_wall", "unassigned_wall"]
    order_index = {zone: idx for idx, zone in enumerate(zone_order)}
    return sorted(faces, key=lambda face: order_index.get(face.zone, 99))


def write_fluent_mesh(
    path: Path,
    points: list[tuple[float, float]],
    cells: list[list[int]],
    boundary_zones_by_edge: dict[tuple[int, int], str],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    cells = orient_cells_ccw(points, cells)
    faces = build_faces(cells, boundary_zones_by_edge)

    n_nodes = len(points)
    n_cells = len(cells)
    n_faces = len(faces)
    cell_types = [FLUENT_CELL_TYPES[len(cell)] for cell in cells]
    mixed_cells = len(set(cell_types)) > 1

    face_groups: dict[str, list[FluentFace]] = defaultdict(list)
    for face in faces:
        face_groups[face.zone].append(face)

    face_zone_ids = {
        "interior": 2,
        "inlet": 3,
        "outlet": 4,
        "top": 5,
        "bottom": 6,
        "plate_wall": 7,
        "unassigned_wall": 8,
    }
    cell_zone_id = 1

    with path.open("w", encoding="ascii") as file:
        file.write('(0 "Generated by Aufgabe1/fluent_mesh_writer.py")\n')
        file.write('(0 "Dimensions:")\n')
        file.write("(2 2)\n\n")

        file.write('(0 "Grid declarations:")\n')
        file.write(f"(12 (0 1 {hx(n_cells)} 0))\n")
        file.write(f"(13 (0 1 {hx(n_faces)} 0))\n")
        file.write(f"(10 (0 1 {hx(n_nodes)} 0 2))\n\n")

        file.write('(0 "Cells:")\n')
        if mixed_cells:
            file.write(f"(12 ({hx(cell_zone_id)} 1 {hx(n_cells)} 1 0)(\n")
            for cell_type in cell_types:
                file.write(f"{hx(cell_type)}\n")
            file.write("))\n\n")
        else:
            file.write(
                f"(12 ({hx(cell_zone_id)} 1 {hx(n_cells)} 1 {hx(cell_types[0])}))\n\n"
            )

        file.write('(0 "Faces:")\n')
        first_face_id = 1
        for zone, zone_faces in face_groups.items():
            last_face_id = first_face_id + len(zone_faces) - 1
            zone_id = face_zone_ids[zone]
            bc_type = FLUENT_BC_TYPES[zone]
            file.write(
                f"(13 ({hx(zone_id)} {hx(first_face_id)} {hx(last_face_id)} "
                f"{hx(bc_type)} 2)(\n"
            )
            for face in zone_faces:
                file.write(
                    f"{hx(face.n0)} {hx(face.n1)} {hx(face.c0)} {hx(face.c1)}\n"
                )
            file.write("))\n\n")
            first_face_id = last_face_id + 1

        file.write('(0 "Nodes:")\n')
        file.write(f"(10 (1 1 {hx(n_nodes)} 1 2)(\n")
        for x, y in points:
            file.write(f"{x:.16e} {y:.16e}\n")
        file.write("))\n\n")

        file.write('(0 "Zones:")\n')
        file.write(f"(39 ({cell_zone_id} fluid fluid 1)())\n")
        for zone, zone_id in face_zone_ids.items():
            if zone not in face_groups:
                continue
            zone_type = FLUENT_ZONE_TYPES[zone]
            file.write(f"(39 ({zone_id} {zone_type} {zone} 1)())\n")
